### ISSUE TITLE
css/less全局引入

### ISSUE THREAD

**Issue by Mqleaf** [quickappcn/issues#1]
### 需求场景
项目会存在一些全局样式，但不能直接在app.ux中引入，需要在各页面引入。不方便，望改善。

例如，在app.ux中引入全局less
`<style lang="less">
@import './assets/styles/style.less';
</style>`
在页面中使用less变量，会报错：
`Variable @text-black is undefined`

**Comment by Mqleaf** [comment]
最好还能像Vue一样，scope区分全局/非全局样式

**Comment by tech-bro-in-vivo** [comment]
嗯，先评估需求，后续答复

**Comment by diydyq** [comment]
这个需求其实很早已经提出来了，实现并不难；
当时处于性能影响，效果不明显，以及其它功能（如：分包，卡片化：卡片目前不加载app.ux），并未启动，该功能的开发；
我们在1060版本中讨论一下，是否增加这项能力；
