### ISSUE TITLE
appRouter sdk 跳转增加https

### ISSUE THREAD

**Issue by pandaSeven** [quickappcn/issues#10]
目前使用appRouter从h5跳转快应用时，location.href为http，是否可以增加https的呢？

**Comment by pandaSeven** [comment]
看到麻烦回复下哈，有这个需求比较急～

**Comment by diydyq** [comment]
抱歉，当前暂不支持！

**Comment by diydyq** [comment]
需求已收到，不过当前未排期；
当开发者有更多需求时，再考虑，因此暂时关闭；
