### ISSUE TITLE
模拟器中device.getCpuInfo返回字段与文档不符

### ISSUE THREAD

**Issue by tnjin** [quickappcn/issues#100]
Issue Type: <b>Bug</b>

通过`device.getCpuInfo()` 方式获取cpu信息，在模拟器中返回的字段与文档中不符。
在模拟器中返回如下：
```
{"cpuIf":"Processor: AArch64"}
```
文档中是 ‘cpuInfo’

Extension version: 1.2.0
VS Code version: 快应用开发工具 3.0.0 (6a8af2336fbc3c8565c68cc5f612772f1c34ff51, 2020-05-22T09:54:18.743Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (4.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by LDbird** [comment]
您好，麻烦加一下我的微信：15701638991，和您详细沟通下

**Comment by LDbird** [comment]
您好，此问题已反馈相关技术同学

**Comment by LDbird** [comment]
您好，此问题IDE已修复；
