### ISSUE TITLE
manifest.json与router

### ISSUE THREAD

**Issue by zhi-he** [quickappcn/issues#101]
### 需求类型

引擎或者不清楚
### 需求描述

文件目录结构为：src/user/address/index.ux
mainfest.json配置为：
“router”:{
  "pages":{
    "user/address":{
         "component": "index"
      }
  }
}
跳转为：
router.push({
      uri: '/user/address'
    })
router.getState()结果为：
{index: 3, name: "PersonalSetting/userAddress", path: "/PersonalSetting/userAddress"}
### 需求场景

快应用的业务复杂后，页面需要分模块，分模块后的manifest.json配置和router跳转，个人感觉不够友好
### 参考

我理想状态是
mainfest.json配置为：
````
“router”:{
  "pages":{
    "address":{
         "component": "/user/address/index",
         "path": "/user/address"
      }
  }
}
````
跳转为：
router.push({
      uri: '/user/address'
    })
router.getState()结果为：
{index: 3, name: "address", path: "/user/address"}
### 联系方式和应用名

微信号：ZZH731701134

我已经尽力描述我的问题了：）

**Comment by diydyq** [comment]
你好，感谢反馈！

在你的例子中，router.getState()应该返回: {index: 3, name: "user/address", path: "/user/address"} 才对呀，怎么返回的是：{index: 3, name: "PersonalSetting/userAddress", path: "/PersonalSetting/userAddress"}；

其实manfest.json中，一个页面在实体层面，推荐是一个文件夹，即：
router: {
  pages: {
    pageDir: {
      component: pageBaseName,
      path: '...' // default is "/pageDir" 
    }
  }
}

这个和你理解不一致的地方在于：pageDir的体现形式上；

**Comment by zhi-he** [comment]
你说的对，是返回的 {index: 3, name: "user/address", path: "/user/address"} ，我写错了。
我只是觉得项目复杂后不能都在pages下一级，多级之后感觉怪怪的，嘿嘿。

**Comment by diydyq** [comment]
这种情况下，你的目录可以层次更深；

pageDir编程一个文件夹的路径，应该也是可以的；
可以参考我们的sample项目：https://github.com/quickappcn/sample
