### ISSUE TITLE
模拟器本地预览功能

### ISSUE THREAD

**Issue by 1115litao** [quickappcn/issues#103]
Issue Type: <b>Feature Request</b>

模拟器本地预览功能 一直显示正在编译 无法运行。重新卸载安装也没用

VS Code version: 快应用开发工具 3.3.0 (ef9455bef7c02e6c6c949005ad53841f264b381b, 2020-08-12T02:36:43.104Z)
OS version: Windows_NT x64 6.1.7601

**Comment by LDbird** [comment]
您好，您那边可以对项目npm i安装下依赖看看；

**Comment by 1115litao** [comment]
npm i执行成功了，但是还是一直在编译，点击运行调试也无反应。

**Comment by LDbird** [comment]
麻烦留下您的联系方式，加您具体沟通下

**Comment by 1115litao** [comment]
WX：13611373042  多谢了

**Comment by LDbird** [comment]
1. 打开目录 C:\Users\{ user }\AppData\Roaming\快应用开发工具
2. 删除目录下所有文件，仅保留 userid
3. 重启 IDE
