### ISSUE TITLE
DEVTOOLS无法使用

### ISSUE THREAD

**Issue by angus1105** [quickappcn/issues#105]
Issue Type: <b>Bug</b>

DEVTOOLS突然无缘无故无法使用了，一直提示web预览页面未加载完成

VS Code version: 快应用开发工具 3.3.0 (ef9455bef7c02e6c6c949005ad53841f264b381b, 2020-08-12T02:35:41.000Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
hap-chimera-toolkit|Hap|1.1.0
hap-vivo-stf|Hap|1.3.3

</details>

**Comment by LDbird** [comment]
您好，您那边是不是IDE的模拟器没有打开，这个没打开的话，web预览也不会有；

**Comment by angus1105** [comment]
> 您好，您那边是不是IDE的模拟器没有打开，这个没打开的话，web预览也不会有；

当然开了，本来好好的突然就不行了

**Comment by LDbird** [comment]
麻烦加下微信，和您具体沟通下：18054264586

**Comment by LDbird** [comment]
![image](https://user-images.githubusercontent.com/48194592/92077142-66263200-edee-11ea-88c4-697c9745edde.png)
devtools无法使用，报上述错误；

解决方式：右键打开ide的安装目录，选resources ->把里面的app文件夹用ide打开->找到路径extensions/hap-devtools/node_modules/hap-devtools-frontend/ux/UxModel.js，格式化下代码；找到如下代码，加上代码  if(!node) { return;  }
![image](https://user-images.githubusercontent.com/48194592/92077474-172ccc80-edef-11ea-9da5-9114ac72e2db.png)
