### ISSUE TITLE
DEVTOOLS

### ISSUE THREAD

**Issue by BestKai** [quickappcn/issues#107]
Issue Type: <b>Bug</b>

DEVTOOLS 查看元素，经常性的选择元素之后右侧样式不能显示当前选择元素的样式。

VS Code version: 快应用开发工具 3.3.1 (21b7a5c4ef8adb950b1ed63b557238a4de866a1c, 2020-09-09T11:49:51.979Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 6, 5|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
hap-chimera-project|Hap|1.1.2
hap-projects|Hap|1.2.4

</details>

**Comment by LDbird** [comment]
您好，这边使用IDE没能复现，麻烦您加下微信：18054264586，和您具体沟通下

**Comment by LDbird** [comment]
您好，现在IDE最新的版本是3.4.0，新版本也没有复现该问题，您那边可以升级下IDE版本；
此issue将关闭，如有问题请再reopen；
