### ISSUE TITLE
修改分辨率布局异常

### ISSUE THREAD

**Issue by JasonToJan** [quickappcn/issues#109]
### 相关信息
- 问题类型

引擎

- 引擎版本

1070以上

- 手机型号

Meizu 16s

- 操作系统

- IDE版本

- toolkit版本

### 问题描述

  修改了手机分辨率，快应用布局异常

### 复现步骤

   1.进入手机设置页面
   2.修改显示大小（即分辨率大小）
   3.返回快应用，部分布局异常
   4.联盟相关代码：（DisplayUtil.java）
![image](https://user-images.githubusercontent.com/30220265/97273942-ec9b4500-186e-11eb-9354-a62e9dcf511e.png)

### 联系方式

c13145f

**Comment by LDbird** [comment]
您好，您的意思是：修改了手机的显示大小，会有屏幕适配的问题；这种情况快应用的宽高等可以使用百分比，不用具体的px；

**Comment by JasonToJan** [comment]
是的，这是一个解决方案。但目前大多数快应用基本都是使用px布局，所以日前已存在的快应用基本都会有此问题，有没有一个折中的处理办法？联盟1070之后才有此问题。

**Comment by izhangshaolin** [comment]
该问题属于联盟内部事务,已拉内部群进行解决
