### ISSUE TITLE
vivo y66 tab滑动闪退问题

### ISSUE THREAD

**Issue by maomaoyp** [quickappcn/issues#11]
- IDE 版本: 1.3.1.0

- hap-toolkit 版本:  toolkit 0.3.1
- 平台引擎版本:  vivo 1030 应用自带   vivo 1040预览版
- 操作系统: win 7 
- node.js 版本: v10.14.2

### 如何复现？

Tab 旋转90度，纵向滑动，  tab-content内image等全屏显示图片。

### 预期效果
滑动不闪退

### 实际效果
滑动20条数据左右闪退到调试开始界面

**Comment by UncleBill** [comment]
刚解决这个问题，准备在下下个版本上线

**Comment by diydyq** [comment]
> 刚解决这个问题，准备在下下个版本上线

这个有进展吗？没有进展，就先close了；
