### ISSUE TITLE
setTimeout 和 setInterval 在IDE中有时会不执行，实机就正常

### ISSUE THREAD

**Issue by liandong00** [quickappcn/issues#110]
Issue Type: <b>Bug</b>

如题

VS Code version: 快应用开发工具 3.4.0 (e9988316cf8370e53960acd40cc5a9735cb48873, 2020-10-20T02:29:52.330Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (8.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
hap-chimera-project|Hap|1.1.2
hap-projects|Hap|1.2.5

</details>

**Comment by izhangshaolin** [comment]
跟ide同学沟通排查,发现为webjs的问题,建议以真机为准,后续会进行修复
