### ISSUE TITLE
1.8.3的debugger，没有读取quickapp.config.js了吗？

### ISSUE THREAD

**Issue by ruofeng086** [quickappcn/issues#112]
![image](https://user-images.githubusercontent.com/14192308/99028346-7dca2580-25aa-11eb-9fa0-e988ce837dcd.png)

quickapp.config.js并没有被执行。

**Comment by ruofeng086** [comment]
![image](https://user-images.githubusercontent.com/14192308/99028457-c7b30b80-25aa-11eb-8094-3d9a4f1db755.png)


手动执行 npm run debug ，则有执行。

**Comment by izhangshaolin** [comment]
已联系开发者，为操作失误，无该问题

**Comment by Weber-Chang** [comment]
我也遇到这个问题，到底是什么失误

**Comment by diydyq** [comment]
最新版本可以吗？应该是很早的时候版本有这个BUG吧；
