### ISSUE TITLE
使用webpack DefinePlugin 会报错

### ISSUE THREAD

**Issue by ruofeng086** [quickappcn/issues#113]
### 相关信息
- 问题类型
不清楚

- 引擎版本
"minPlatformVersion": 1073,

- 手机型号
redmi a8

- 操作系统
macos 10.15.7

- IDE版本
没有用ide，ide没有读取quickapp.config.js，改用vscode了

- toolkit版本
1.8.3

### 问题描述
quickapp.config.js 中使用了 webpack.DefinePlugin ，代码中使用会报错
![image](https://user-images.githubusercontent.com/14192308/99057588-f646db80-25d6-11eb-92e0-5beb8a14a89b.png)
![image](https://user-images.githubusercontent.com/14192308/99057602-fc3cbc80-25d6-11eb-9522-1fa2f9e984de.png)
![image](https://user-images.githubusercontent.com/14192308/99057615-019a0700-25d7-11eb-9212-23fb78f43e0d.png)

### 联系方式

ruofeng168

**Comment by izhangshaolin** [comment]
已联系开发者，为操作失误，无此问题
