### ISSUE TITLE
原生广告没有处理事件url 只有上报地址

### ISSUE THREAD

**Issue by StarfishW** [quickappcn/issues#116]
### 需求类型

不清楚
### 需求描述

在使用原生广告时，onload返回值中缺少一些参数，例如返回下载任务，但是没有下载的地址
### 需求场景

点击广告执行下载任务，点击广告跳转其他外部应用
### 参考

https://doc.quickapp.cn/features/service/ad.html#%E5%8E%9F%E7%94%9F%E5%B9%BF%E5%91%8A
### 联系方式和应用名

微信号 ： wyq767190
应用正在开发中 未上架

**Comment by izhangshaolin** [comment]
跟开发者沟通了解,开发者需求为使用原生广告时,无法对广告的曝光,点击等一些行为进行处理,该需求已在后续的1090版本中，对该功能有了相关的支持!
