### ISSUE TITLE
 windows 10 npm安装hap-toolkit成功 但hap -v命令无效，已多次卸载安装无果。。不知道什么原因

### ISSUE THREAD

**Issue by ForAFuture** [quickappcn/issues#117]
具体内容就显示无法识别，难道需要设置环境变量吗？官网也没说需要设置呀~
我实在快应用的终端里面安装的

**Comment by izhangshaolin** [comment]
无需设置环境变量     
  通过 npm 仓库安装，在命令行中执行以下命令：
     npm install -g hap-toolkit
  在命令行中执行hap -v会输出版本信息表示hap-toolkit安装成功，如下命令所示：
    hap -v
麻烦确定下输入对应命令是否正确   以及输入后的反馈结果    可加微信： xiaomi_kuaiyigyong

**Comment by diydyq** [comment]
`npx hap-toolkit init quickappDemo`也可以的；
由于没有回应，先close，如有需要请重新打开，谢谢；
