### ISSUE TITLE
如何在 Windows、MacOS 上安装 adb

### ISSUE THREAD

**Issue by tech-bro-in-vivo** [quickappcn/issues#120]
顾名思义，Android Debugging Bridge（ADB）是一个命令行实用程序，允许开发人员调试其应用程序的各个部分。但是，它不仅限于开发人员。如果您想访问其他无法访问的 Android 平台功能，则也可以通过在计算机上安装 ADB，来使用 ADB 命令，无论是 Windows，macOS，Linux 还是 Chrome OS。安装后，您可以在 Android 设备上使用 ADB 进行[许多有趣的操作](https://beebom.com/cool-things-adb-lets-you-do-android-device/)。本文就“如何在 Windows、MacOS 上安装 adb“，跟大家探讨下。

**备注**：如果您已经安装如 [Android Studio](https://developer.android.com/studio) 开发构建工具，它已经自带 ADB，无需考虑额外安装。

## 在 Windows 上安装 ADB

- 首先，从 Google 的官方页面下载[适用于 Windows](https://dl.google.com/android/repository/platform-tools-latest-windows.zip) 的 [ADB 平台工具](https://dl.google.com/android/repository/platform-tools-latest-windows.zip)。下载完成后，使用 [WinRAR 之类](https://beebom.com/winzip-winrar-alternatives/)的[文件归档器实用程序](https://beebom.com/winzip-winrar-alternatives/)在 Windows PC 上提取此文件的内容。
- 现在转到提取的文件夹，然后单击地址栏。现在，键入“ cmd”，然后按 Enter。随即，将在 ADB 目录中打开一个命令提示符窗口。
- 之后，将您的 Android 设备连接到 Windows PC 并执行`adb devices`命令。
- 它将在智能手机上提示“**USB 调试**”提示。启用“**始终允许**”复选框，然后点击“允许”。
- 现在，您应该在“命令提示符”窗口中看到设备的序列号。如果它没有检测到您的设备，然后 `adb devices` 再次运行，这一次，它肯定会检测到您的设备。恭喜你！现在，ADB 已成功安装在 Windows PC 上。

**备注**：需要补充说明的是，如果你下次想在 Terminal 任意路径下，都可以调用 ADB 命令，那么您需要将 _ADB.exe_ 所在的路径，加入到环境变量。

## 在 MacOS 上安装 ADB

在这里，我们将采用略有不同的路径在 macOS 上安装 ADB。我们必须先在 macOS 上安装 Homebrew，然后才能轻松安装 Android 平台工具。Homebrew 是一个[开源](https://beebom.com/open-source-apps-android/)软件包管理器，用于安装缺少的软件包。综上所述，我们从这里开始。

- 首先，在 Mac 上打开终端并执行以下命令。它将在您的 Mac 上安装 Homebrew。在安装过程中，可能会要求您输入密码。整个安装过程大约需要 10 分钟。

```bash
ruby -e $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)
```

- 然后，从以下命令安装 ADB 平台工具。

```bash
brew cask install android-platform-tools
```

- 现在，将 Android 设备连接到 Mac 并执行 `adb devices` 命令。您将在 Android 设备上收到提示，以允许进行 USB 调试。因此，只需启用该复选框并点击“允许”。
- 现在，您应该在 Mac 上看到设备的序列号，这表明 ADB 已成功安装在 Mac 上，恭喜。

## 在设备上启用 adb 调试

如要在通过 USB 连接的设备上使用 adb，您必须在设备的系统设置中启用 **USB 调试**（位于**开发者选项**下）。如需在通过 WLAN 连接的设备上使用 adb，请参阅[通过 WLAN 连接到设备](https://developer.android.com/studio/command-line/adb#wireless)。

在搭载 Android 4.2 及更高版本的设备上，“开发者选项”屏幕默认情况下，处于隐藏状态。如需将其显示出来，请依次转到**设置 > 关于手机**，然后点按**版本号**七次。返回上一屏幕，在底部可以找到**开发者选项**，并**启用“ USB调试”**。无论何时将 Android 设备连接到计算机，都选择“文件传输（MTP）”模式。如此，您即可以通过 ADB 来操控您的手机（如调试、设置、刷机等等）。

关于 ADB 更多文章，可以参考：

- [Android 调试桥 (adb) - Google Android Studio Document](https://developer.android.com/studio/command-line/adb)
- [How to Install ADB on macOS](https://stackoverflow.com/questions/31374085/installing-adb-on-macos)
- [How to Install ADB on Windows, macOS, Linux, and Chrome OS](https://beebom.com/how-to-install-adb-windows-mac/)

**Comment by tech-bro-in-vivo** [comment]
您只有在开发环境，有安装 `adb` 工具，才能通过命令行，来查看快应用输出日志；

```bash
adb logcat -s LOGCAT_CONSOLE
```

注意，如果您的快应用引擎是 1030 或以前版本，请运行以下命令：

```bash
adb logcat -s JsConsole
```

 当然，您也可以[利用 devtools 调试界面 console 输出](https://doc.quickapp.cn/ide/cli-debug.html?h=adb#%E5%88%A9%E7%94%A8-devtools-%E8%B0%83%E8%AF%95%E7%95%8C%E9%9D%A2-console-%E8%BE%93%E5%87%BA)日志，从而调试 JS 代码。

**Comment by RaldLukka** [comment]
使用brew cask命令会报错 Unknown command cask
直接brew install即可

**Comment by jiangxiaohui000** [comment]
`adb server version (40) doesn't match this client (41); killing...
* daemon started successfully
List of devices attached
error: protocol fault (couldn't read status): connection reset
`
这是怎么回事
