### ISSUE TITLE
失去焦点blur事件无效

### ISSUE THREAD

**Issue by darlings** [quickappcn/issues#13]
### 需求类型
不清楚

### 需求描述
失去焦点blur无效

### 需求场景
input输入框失去焦点时，需要光标消失并且收起键盘

### 联系方式和应用名

微信号：duanjiamei002

**Comment by lqzerogg** [comment]
OK，收集需求了

**Comment by diydyq** [comment]
开发者可以通过 this.$element('input').focus({ focus: false }) 来收起键盘；
有workaround，因此关闭；
