### ISSUE TITLE
与webview 通讯 onmessage 事件有bug

### ISSUE THREAD

**Issue by jinwyp** [quickappcn/issues#14]
### 相关信息
- 问题类型 按照文档中,非常简单的代码范例都有如下2个bug

https://doc.quickapp.cn/widgets/web.html

system.onmessage = function(data) {
  console.log('message received: ' + data)
}
system.postMessage('hello')

1 bug1 : 使用 onmessage 和  postMessage 与webview, 通讯时,    当快应用中使用postMessage 传递消息后, 在webview 的onmessage无法接受到消息. 现象就是没任何反应, webview 中的system.onmessage没有任何触发运行.

2 bug2:  在webview 中 使用 postMessage 给快应用传消息后, 会触发 webview 的 system.onmessage 事件, 导致接受到上一次的快应用通过postMessage的发出的消息.   期望: 应该不触发onmessage事件. 

- 引擎版本
所有机型的1020版本都有此问题, 包括 vivo , 华为大部分机型.

**Comment by diydyq** [comment]
感谢提出问题；
我们试了一下没有这样的问题，否则当时在发版时就应该存在这样的问题；
会不会有其它更深的复现场景，您可以邮件yanming5@xiaomi.com留下联系方式；
我们的同事来跟进具体代码与机型表现；

**Comment by jinwyp** [comment]
技术论坛已经说过这个问题 https://bbs.quickapp.cn/forum.php?mod=viewthread&tid=1187

4 网页给快应用发信息时,快应用发送给网页的信息才会带回
这句话就是我说的问题bug2.

**Comment by jinwyp** [comment]
https://bbs.quickapp.cn/forum.php?mod=viewthread&tid=1437
这个帖子也提到要轮询, 但解决问题的根本是有bug才需要轮询.  正常不应该需要轮询.


现在必须不停的 在webview 中 使用postMessage 给快应用发消息, 才能收到快应用中通过postMessage给webview发的消息.

```
function loopInterval() {

  stopIntervalId = setTimeout( function () {

    if (quickResult && quickResult.installShortcutSuccess) {
      clearTimeout(stopIntervalId);
      return;
    }
    window.system.postMessage(JSON.stringify({ }))
    loopInterval()
  }, 1500);
}
```

**Comment by YanMr** [comment]
亲自验证，并在微信群中演示，没有出现对应的问题！如果还有问题，我拉一个微信群，请在里面讨论

**Comment by diydyq** [comment]
经过验证，未复现开发者提出的问题；
如果问题仍然存在，麻烦请留下联系方式，并reopen该问题；
暂时关闭；

**Comment by LeeeeeeM** [comment]
> ### 相关信息
> * 问题类型 按照文档中,非常简单的代码范例都有如下2个bug
> 
> https://doc.quickapp.cn/widgets/web.html
> 
> system.onmessage = function(data) {
> console.log('message received: ' + data)
> }
> system.postMessage('hello')
> 
> 1 bug1 : 使用 onmessage 和 postMessage 与webview, 通讯时, 当快应用中使用postMessage 传递消息后, 在webview 的onmessage无法接受到消息. 现象就是没任何反应, webview 中的system.onmessage没有任何触发运行.
> 
> 2 bug2: 在webview 中 使用 postMessage 给快应用传消息后, 会触发 webview 的 system.onmessage 事件, 导致接受到上一次的快应用通过postMessage的发出的消息. 期望: 应该不触发onmessage事件.
> 
> * 引擎版本
>   所有机型的1020版本都有此问题, 包括 vivo , 华为大部分机型.

有热心开发者提供dem代码。
https://www.notion.so/Bug-7823c14b9b4341078cd46bb54c4fcce8   第6条。
在
```
this.$element('subwayWeb').postMessage({ message: postData });
```

之后执行

```
this.$forceUpdate()
```


```
this.$element('subwayWeb').postMessage({ message: postData });
this.$forceUpdate();
```
