### ISSUE TITLE
全面屏手机底部按钮栏是否显示监听

### ISSUE THREAD

**Issue by Sandanman** [quickappcn/issues#15]
### 需求类型

不清楚

### 需求描述

全面屏手机的底部按钮栏使用户可以控制显示、隐藏的，在按钮栏不变的前提下获取的高度是ok的，但是在底部按钮栏显示状态改变时，高度依旧是状态栏改变之前的高度。
建议，添加底部按钮栏状态监听事件，以便用户自适应屏幕高度以给用户更好的体验。

### 需求场景

在自定义titleBar的情况下，页面以上部分为四个大分类位置固定，页面下部分为list（参考快应用【周边生活排行】），需要根据是否有底部按钮栏来设置list的高度

### 参考

可参考【百度地图app】用户手动改变底部按钮栏显示时，地图的自适应（需求场景、参考可以通过微信联系，有录屏信息）

### 联系方式和应用名

微信号 15832975272  快应用 周边生活排行

**Comment by lqzerogg** [comment]
了解，我们调研一下

**Comment by tech-bro-in-vivo** [comment]
跟 @Sandanman 沟通之后，确认使用flex可以满足需求。不建议使用计算高度的方式适配，而应该采用自适应的方式适配屏幕
