### ISSUE TITLE
动画属性transform-origin无效

### ISSUE THREAD

**Issue by hejiaoshou** [quickappcn/issues#16]
### 相关信息
- 问题类型
不清楚

- 引擎版本
1020

- 手机型号
魅族16th、荣耀8、三星s9、索尼xz2

### 问题描述
    transform: rotate(90deg);
    transform-origin: 0px 0px;
元素旋转时，设置origin无效

### 联系方式
wx：hejiaoshou811

**Comment by YanMr** [comment]
感谢您的提供，这个确实是个BUG,我们1050版本会修复好！谢谢您的支持～

**Comment by LDbird** [comment]
您好，此问题已在1060版本修复，请更新至1060版本使用
