### ISSUE TITLE
template里使用ES6的字符串拼接出现this.字符的bug

### ISSUE THREAD

**Issue by linxiaobiao** [quickappcn/issues#17]
- 问题类型
不清楚

- 引擎版本
预览版 1040

- 手机型号
华为 荣耀 Honor Magic（应该不分手机型号都有）

- 操作系统
Mac OS 

- toolkit版本
toolkit 0.2.1

### 问题描述
  1.预期效果：
<text>{{ true ? `满${couponData.discount_amount}可使用` : '下单立减'}}</text>
能够正常解析
  2.实际效果：填写中文或者英文出现this.字符，填写数字则正常

### 复现步骤
```html
  <text>{{ true ? `满${couponData.discount_amount}`: '下单立减'}}</text>
```

### 联系方式
a283650221

**Comment by UncleBill** [comment]
@linxiaobiao 你好，感谢反馈！我们会尽快修复的

**Comment by scriptsman** [comment]
问题已解决，请更新toolkit至0.5.4版本
