### ISSUE TITLE
使用web组件，fixed元素失效

### ISSUE THREAD

**Issue by 1360659646** [quickappcn/issues#18]
### 相关信息
- 问题类型
不清楚

- 引擎版本
1020

- 手机型号
vivox6s，小米9

- 操作系统
windows 10

### 问题描述

  使用web组件，在H5页面中的fixed元素失效

### 复现步骤
  
<img width="732" alt="1" src="https://user-images.githubusercontent.com/44384960/55857352-773e2580-5b9f-11e9-83a2-5d0014f33a0a.png">
<img width="744" alt="2" src="https://user-images.githubusercontent.com/44384960/55857353-773e2580-5b9f-11e9-97d4-c5f3383b37f1.png">

### 联系方式
wx：15294995462

**Comment by YanMr** [comment]
你好，我这边测试验证了下，没有复现你说的问题，建议检查下fixed布局是否规范或者被其他元素影响，再不然，写一个简单的demo示例排查下！

**Comment by YanMr** [comment]
问题已经解决，原因：开发者代码template下没有跟节点包裹web组件原因
