### ISSUE TITLE
能否增加一个类似Vue的filter功能

### ISSUE THREAD

**Issue by Wlisfes** [quickappcn/issues#19]
### 需求类型
不清楚

### 需求描述
在html代码中过滤文本、替换文本等

### 需求场景
比如一个歌曲的播放量十250000，页面上传入数字可以返回25万

### 参考
参考尤大大的Vue框架  👉https://cn.vuejs.org/v2/guide/filters.html

### 联系方式和应用名
微信：ut77243   
快应用： 周公AI解梦

**Comment by diydyq** [comment]
您好，过滤器的一些用法已经通过toolkit发版支持，请使用 hap-toolkit@0.4之后的版本试下；
大概的filter用法如下，后面我们将在官方文档中更新描述；
----
过滤器应该被添加在表达式的尾部，由“管道”符号指示，filter 指令形式如下：
{{ message | capitalize }}
通过 hap-toolkit 转换为 function () {return this.capitalize(this.message)}
过滤器函数总接收表达式的值 (之前的操作链的结果) 作为第一个参数。在上述例子中，capitalize 过滤器函数将会收到 message 的值作为第一个参数。
 
过滤器可以串联：
{{ message | filterA | filterB }}
在这个例子中，filterA 被定义为接收单个参数的过滤器函数，表达式 message 的值将作为参数传入到函数中。然后继续调用同样被定义为接收单个参数的过滤器函数 filterB，将 filterA 的结果传递到 filterB 中。
 
过滤器是 JavaScript 函数，因此可以接收参数：
{{ message | filterA('arg1', arg2) }}
这里，filterA 被定义为接收三个参数的过滤器函数。其中 message 的值作为第一个参数，普通字符串 'arg1' 作为第二个参数，表达式 arg2 的值作为第三个参数。
 
过滤器在页面导出的对象中定义。
 
开发者写法：
<template>
 <div class="demo-page">
  <text class="title">{{ message | capitalize }}</text>
 </div>
</template>


<script>
export default {
 private: {
  message: 'hello'
 },
 capitalize(value) {
  if (!value) return ''
  value = value.toString()
  return value.charAt(0).toUpperCase() + value.slice(1)
 }
}
</script>
 
一些转换示例：
{{ value | filter }} 转换为 function () {return this.filter(this.value)}
{{ value | filterA | filterB }} 转换为 function () {return this.filterB(this.filterA(this.value))}
{{ value | filter("arg1", arg2) }} 转换为 function () {return this.filter(this.value,"arg1",this.arg2)}
