### ISSUE TITLE
联盟应该有个统一 第三方授权登录接口

### ISSUE THREAD

**Issue by caiwzhou** [quickappcn/issues#20]
氧气听书 

 
我这边 数据来看，登录2/3 来自微信
日常中大家还是不喜欢用 手机加密码登录 毕竟要注册麻烦

而且 微信，QQ，新浪第三方有一定局限性

**Comment by homercs** [comment]
@caiwzhou 能详细描述一下什么是统一第三方授权登录接口吗？

**Comment by lqzerogg** [comment]
目前是支持三方的微博，微信以及QQ登录

**Comment by 77chenmei** [comment]
开发者未回复，暂时关闭该问题，有需求再reopen该问题
