### ISSUE TITLE
能增加一个类似list组件的区域滚动的组件或者修改一下list组件

### ISSUE THREAD

**Issue by Wlisfes** [quickappcn/issues#21]
### 需求描述
list组件的局限性  内部必须使用list-item  list-item内部又不能是用if  其实我用shwo也导致出现页面数据错乱的bug  内部实现使用if or show其实可以解决很多问题

### 需求场景
不如聊天界面布局  上部分是聊天纪录区域 使用一个list  底部是输入框  list-item是每一条聊天纪录  在快应用中的text组件又无法识别/n这种换行符号 所以只能吧文字截取成数组for出来实现文字换行  不一样的时候难免结构不一致导致bug

### 参考
参考better-scroll组件库  https://github.com/ustbhuangyi/better-scroll

### 联系方式和应用名
微信：ut77243   快应用：周公AI解梦

**Comment by lqzerogg** [comment]
ok，我们先调研一下

**Comment by knivesrises** [comment]
list-item已经支持 if for 等渲染指令了
