### ISSUE TITLE
无法正常编译

### ISSUE THREAD

**Issue by Yechuanjie** [quickappcn/issues#22]
Issue Type: <b>Bug</b>

快应用开发工具 manifest.json 文件中 router 下包含 widgets 字段，工具无法正常编译且会导致扩展程序崩溃
### manifest.json
```json
"router": {
    "entry": "pages/index",
    "pages": {
      "pages/index": {
        "component": "index",
        "path": "/pages/index"
      },
      "pages/quickcard": {
        "component": "index",
        "path": "/pages/quickcard"
      }
    },
    "widgets": {
      "pages/quickcard": {
        "name": "快应用卡片",
        "description": "时间你好",
        "component": "index",
        "path": "/pages/quickcard",
        "features": [
          {
            "name": "system.router"
          }
        ]
      }
    }
 }
```
### 开发工具编译
![image](https://user-images.githubusercontent.com/18052499/56873580-e05dde00-6a65-11e9-938b-b513e0466bdd.png)

quickapp IDE version: 快应用开发工具 1.3.1 (d310113bfb1eb7a7ee95b78991aa8fe4ca4a5d51, 2019-03-30T08:43:00.376Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by lqzerogg** [comment]
请问你做的是哪一家的卡片规范呢？目前联盟标准的卡片还没有推出，所以目前开发工具是还不支持的。

**Comment by lqzerogg** [comment]
许久没有回复，先关闭
