### ISSUE TITLE
页面 onHide 中发送 get 请求。在应用启动进入口页面，点击返回按钮退出应用时，请求正常发送，但是控制台会有报错

### ISSUE THREAD

**Issue by koala0521** [quickappcn/issues#23]
### 相关信息
- 问题类型: 不清楚

- 引擎版本 : 1040

- 手机型号: vivo X21UD A

- 操作系统 : windows8 & Mac OS 10.14

- IDE版本 : 1.3.1

- toolkit版本 : 0.4.3

### 问题描述

    1. 预期效果：页面onHide中发送get请求。在应用启动进入口页面，点击返回按钮退出应用时，请求正常发送，无报错。
    2. 实际效果：页面onHide中发送get请求。在应用启动进入口页面，点击返回按钮退出应用时，请求正常发送，控制台会有报错。
    3. 错误栈：

```    
    (unknown) Error: execInvokeCallback: 无效invoke回调Id "3"
    c.error.e @ VM9:1
    global.(anonymous function).n @ VM9:1

```

### 复现步骤

    复现步骤：

    1. 入口页面 onHide 周期中发送 get 请求；
    2. 点击启动调试，调起 chrome 调试器；
    3. 点击返回按钮退出应用时，控制台会有报错。

### 联系方式

    wx： 328762691

**Comment by UncleBill** [comment]
@diydyq  看下这个问题

**Comment by diydyq** [comment]
这个报错应该不影响用户的正常体验吧；
onHide()中异步请求，之后应该是页面销毁后，对应的异步response返回，发现不存在了，所以输出一个error；
如果不影响正常的用户逻辑，就暂时先保持当前输出方式；
