### ISSUE TITLE
自定义组件动态修改样式不生效

### ISSUE THREAD

**Issue by koala0521** [quickappcn/issues#24]
### 相关信息
- 问题类型: 引擎

- 引擎版本 : 1040

- 手机型号: vivo X21UD A

- 操作系统 : Mac OS 10.14

- IDE版本 : 1.3.1

- toolkit版本 : 0.4.3

### 问题描述

1. 预期效果：自定义组件通过传参，动态修改组件内部 css 样式 font-size 、color ，样式应该正常生效。
2. 实际效果：动态修改样式无效。

### 复现步骤

    复现步骤：

    1. 创建自定组件，在使用组件页面 import 并给组件传递参数。
    2. 自定组件接收参数，并动态修改样式。
    3. 修改未生效。

### 联系方式

    wx： 328762691

**Comment by scriptsman** [comment]
您好，微信搜不到，请加下我吧 wx: vivo-technology

**Comment by diydyq** [comment]
麻烦提供一下相关示例代码，也可能与开发者写法有关；
如后面无跟进，将被迫关闭；
