### ISSUE TITLE
希望支持在电脑谷歌浏览器控制台输出websokect的真实调用信息

### ISSUE THREAD

**Issue by shaofeiwebs** [quickappcn/issues#26]
### 需求场景
正在开发一款IM及时通讯的快应用，真机上调试不方便
### 联系方式和应用名

remember7758258

**Comment by diydyq** [comment]
你的意思是说：在Network中体现交互的信息？还是 console中手动输出 websocket 信息，存在BUG？

**Comment by shaofeiwebs** [comment]
> 你的意思是说：在Network中体现交互的信息？还是 console中手动输出 websocket 信息，存在BUG？

现在调试websocket的时候  在pc的控制台里提示 在控制台里是假数据  想console真实数据要去真机上看 想在控制台里就打印出真实的数据

**Comment by diydyq** [comment]
那您说的这个需求可以理解为：在Network中增加websocket的数据，就可以解决问题吧；
需求已记下，@SusanPan后续会调研增加该功能！
