### ISSUE TITLE
tab-content是否可以设置取消预加载？

### ISSUE THREAD

**Issue by Wlisfes** [quickappcn/issues#27]
### 联系方式和应用名

微信：UT77243    快应用：算命占卜

**Comment by lqzerogg** [comment]
快应用目前是native渲染的，然后native的基础控件会默认预加载左右一页。短期内应该不会对这个进行修改。有需求的可以点下赞，点赞数多的话可以会考虑纳入规划

**Comment by diydyq** [comment]
预加载的功能：是说在某个页签点击的时候才完成加载并渲染，而不是最开始页面渲染的时候；
如果是这样，那你可以在每个页签中增加if指令来控制，监听tab的change事件，当index相同时才加载；
相关文档可以参考：https://doc.quickapp.cn/tutorial/widgets/tabs-tutorial.html
