### ISSUE TITLE
App Framework ### 容器已销毁,接口调用(system.fetch.fetch())无效

### ISSUE THREAD

**Issue by 737** [quickappcn/issues#28]
Issue Type: <b>Bug</b>

跳转的时候报这个警告
App Framework ### 容器已销毁,接口调用(system.fetch.fetch())无效

quickapp IDE version: 快应用开发工具 1.4.0 (31949c870eaf2bd41b4eb0fed14083b6ccab58fd, 2019-05-07T07:16:04.121Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (7.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by scriptsman** [comment]
您好，方便留一下联系方式吗？

**Comment by 737** [comment]
liwl@ctrip.com

发件人: scriptsman <notifications@github.com>
发送时间: 2019年5月28日 17:56
收件人: quickappcn/issues <issues@noreply.github.com>
抄送: lwl李文利 <liwl@Ctrip.com>; Author <author@noreply.github.com>
主题: [External]Re: [quickappcn/issues] App Framework ### 容器已销毁,接口调用(system.fetch.fetch())无效 (#28)


您好，方便留一下联系方式吗？

**Comment by scriptsman** [comment]
沟通后发现出现该问题的原因与业务代码逻辑相关性较大，建议整改
