### ISSUE TITLE
希望1040的release包带上版本和时间信息

### ISSUE THREAD

**Issue by makeng** [quickappcn/issues#31]
### 需求类型
toolkit 

### 需求描述
「1040」版本生成的「rpk」包不再有「版本和时间」信息，希望像「1030」以前那样带上信息。

### 需求场景
方便持续集成和管理

### 联系方式和应用名
- 邮箱：810768333@qq.com
- 微信：z158758158758

![image](https://user-images.githubusercontent.com/23654388/58540477-08d72480-822c-11e9-8826-8312cc7b1b8a.png)

**Comment by UncleBill** [comment]
我们认为这样文件会比较乱，且大部分人不太需要这个，所以去掉了。后续我们打算添加一条配置参数，提供类似命名模板的配置，让大家可以自定义文件名。

在此之前你可以考虑添加一条 npm script hook，如 `postbuild`，通过它来执行重新命名脚本。
