### ISSUE TITLE
refresh组件与tabs组件嵌套问题

### ISSUE THREAD

**Issue by gug000** [quickappcn/issues#32]
目前tab-content组件下嵌套refresh组件在IDE上没法显示，希望可以解决这个问题，否则开发起来还是很痛苦的，只能真机调试

**Comment by Mqleaf** [comment]
无法复现该问题，且没有提供复现代码，无法确认问题点。

**Comment by diydyq** [comment]
麻烦请提供一些清晰的代码示例与联系方式；先暂时close，提供后再open；
