### ISSUE TITLE
数组内元素更新后，UI组件不更新

### ISSUE THREAD

**Issue by makeng** [quickappcn/issues#33]
- 手机型号
全部

### 问题描述
数组类型的数据，数据更新后列表组件无法获取最新的数据，无法更新UI。

### 复现步骤
普通 for 生成组件列表，然后更新数据。
- 尝试 $forceUpdate，无效
- 尝试 splice 数组重新插入数据，无效

html部分，就是普通的 for 生成一系列自定义组件：
`                <div class="time-list fxd-c fx-1">
                    <time-item for="{{list}}"
                               subname="{{$item.title}}"
                               active="{{$item.active}}"
                               desc="{{$item.desc}}"
                               @click="onItemClick($item.id)"
                               @change="onItemStatusChange($item.id)"
                    ></time-item>
                </div>`

而 TimeItem 内部，样式根据属性 active 产生变化：
`            <text class="time-display-name {{active ? 'active':'inactive'}}">
                {{name}}
            </text>`

JS：
      const list = JSON.parse(JSON.stringify(this.list));
      const item = list.find(item => item.id === id);
      item.active = newStatus; // 改变状态，结果却无效
      this.list = list;

![image](https://user-images.githubusercontent.com/23654388/59175975-1d9bac80-8b8a-11e9-8219-5157f5a83897.png)

### 联系方式
微信：z158758158758

**Comment by LeeeeeeM** [comment]
有没有代码，贴一下可以吗。

**Comment by makeng** [comment]
> 有没有代码，贴一下可以吗。

有的，已经贴上。初始化时组件能根据 active 渲染，更新就不能。

**Comment by LeeeeeeM** [comment]
> > 有没有代码，贴一下可以吗。
> 
> 有的，已经贴上。初始化时组件能根据 active 渲染，更新就不能。

```javascript
const list = JSON.parse(JSON.stringify(this.list));
const item = list.find(item => item.id === id);
item.active = newStatus; // 改变状态，结果却无效  --->  这里的item 和 list是两个数组，这里有问题。用带有副作用的方法去处理吧
this.list = list;
```

**Comment by xuwenqing2014** [comment]
你好，这个问题解决了么，也也出现了，视图不更新，很是着急

**Comment by LDbird** [comment]
页面感受不到数组中的某条数据改变，可以使用$set方法，页面可以更新；
可参考文档：https://doc.quickapp.cn/framework/script.html?h=%24set

**Comment by makeng** [comment]
> 你好，这个问题解决了么，也也出现了，视图不更新，很是着急

关于快应用版本 1.4.0 的「数组内部对象更新」，我的记录的方法有：
* ✔️副作用方法
* ✔️key 更新
* ✔️ 赋值 2 次（this.list = [] this.list = newList）缺点是数组会闪动
* ❌ $forceUpdate 
* ❌ $set 
* ❌ 深复制
至于新版本哪些有效，你可以实验下。期待你的回复。
