### ISSUE TITLE
1050多层级退回 会有渲染样式错乱问题

### ISSUE THREAD

**Issue by liuxiankunkun** [quickappcn/issues#37]
### 相关信息
- 问题类型

- 引擎版本

平台：快应用预览版 1050

- 手机型号

测试机型: vivo X20A 

- 操作系统

- IDE版本

- toolkit版本

### 问题描述

问题描述：快应用程序进入多层级页面，逐层返回 操作过快的话就会有样式错乱问题（连续点击5～6次回退就会有样式渲染问题）

### 复现步骤

我们的需求是：详情页面有推荐板块，推荐板块进入的还是详情页，所以会有重复把页面加入页面栈的情况，然后连续点击5～6次返回，页面就会样式错误

### 联系方式

微信号：15210202794

**Comment by diydyq** [comment]
感谢反馈；上周已经修复问题并入库，接下来的1050版本在各厂家灰度时会表现正常；
不过预览版1050暂未更新，请了解；
