### ISSUE TITLE
【优化无效】手册上的「结构优化」策略无效

### ISSUE THREAD

**Issue by makeng** [quickappcn/issues#38]
### 相关信息
- 问题类型
引擎 

- 引擎版本
1040

- 操作系统
Mac OS 10.14

- IDE版本
Webstorm 2018

- toolkit版本
toolkit 0.4.7 

### 复现步骤
两个自定义库函数对象，合计约 6 KB：
![image](https://user-images.githubusercontent.com/23654388/60645241-c62bec00-9e6a-11e9-99c1-bdb22314aeac.png)

一开始各个 ux 文件以 import 方式引入，为了减少 rpk 体积，改为使用 this.$app.$def 方式引入：
![image](https://user-images.githubusercontent.com/23654388/60645340-02f7e300-9e6b-11e9-92ca-317d65f51e05.png)

使用方式如：
      this.$app.$def.storage.set(this.deviceId, "status", this.status)

所有代码运行都是是没有问题的。只是编译出来的 rpk，从 823KB，缩减到 822KB，感觉优化是无效的。
![image](https://user-images.githubusercontent.com/23654388/60645595-a8ab5200-9e6b-11e9-80fc-fd809071b8be.png)

build 文件夹下的代码，这两个对象的内容依然到处都是，如何清晰地知道优化策略起效？
![image](https://user-images.githubusercontent.com/23654388/60645670-e314ef00-9e6b-11e9-86c3-34230060289d.png)

### 联系方式
wx：158758158758z

**Comment by diydyq** [comment]
是不是除了app.ux引入之外，其它的页面ux或者js也直接或者间接的引入了这个js呢？
需要说明的是：页面ux或者间接引入的js不要import/require这个js就能解决问题；

**Comment by makeng** [comment]
> 是不是除了app.ux引入之外，其它的页面ux或者js也直接或者间接的引入了这个js呢？
> 需要说明的是：页面ux或者间接引入的js不要import/require这个js就能解决问题；

是的。除了 ux，还要把 js 文件里面的引用去掉才行，去掉之后文件大小 797KB，少了 26KB。

**Comment by makeng** [comment]
希望新版本能改进一下，因为大的库还能挂在 $def 下，那些分列的小的就不行了（比如正则校验函数），数量太多。
