### ISSUE TITLE
web组件中trustedurl使用正则后，页面不能与快应用通信

### ISSUE THREAD

**Issue by Masterzyy** [quickappcn/issues#40]
### 相关信息
- 问题类型
引擎 

- 引擎版本
预览版1040

- 手机型号
Redmi note 3

- 操作系统

- IDE版本

- toolkit版本

### 问题描述
1.预期效果：web组件中的trustedurl写入匹配的正则后，加载的页面可与快应用通信
2.实际效果：使用正则后，加载的页面仍无法与快应用通信

### 复现步骤
react写的单页面应用中，使用web组件加载单页面应用
     <web
        id="eduWeb"
        src="{{eduWebSrc}}"
        trustedurl="{{lists}}"
        allowthirdpartycookies="{{allowthirdpartycookies}}"
        onpagestart="{{onPageStart}}"
        onerror="{{onError}}"
        onmessage="{{onMessage}}"
      ></web>
![image](https://user-images.githubusercontent.com/31351545/60693776-2758cb80-9f0e-11e9-9754-9c7f2e649412.png)

src中eduWebSrc代表应用首页地址 https://devh5-study.hismarttv.com/mobile/spa/home
trustedurl中的lists正则写的是 lists: `[/https:\/\/devh5-study\.hismarttv\.com\/.*/]`
src的地址下是可以正常通信的，跳转到其他路由下由于页面地址的改变，无法再通信。

页面向快应用通信：
```javascript
  // 往快应用发送消息
  postMsg2QuickApp = (action, data) => {
    const msg = JSON.stringify({
      action,
      data
    });
    window.system.postMessage(msg);
  }
快应用在onMessage中接收：
  onMessage(e) {
    // message格式：
    // {
    //   // 动作，表示要干什么
    //   action: 'xxxx',
    //   // 数据，该动作附带的额外数据
    //   data: 'xxxx'
    // }
    console.log(JSON.stringify(e));
  },
```

### 联系方式
微信号:  z956174725

**Comment by 77chenmei** [comment]
host 相同，建议只匹配host [/^host/]

**Comment by Masterzyy** [comment]
正则已修改为[/^https:\/\/devh5-study\.hismarttv\.com/]，还是不能通信

**Comment by 77chenmei** [comment]
麻烦把不能通信的url发给我，谢谢

**Comment by Masterzyy** [comment]
url形式如： https://devh5-study.hismarttv.com/mobile/spa/home?distributeId=2000#/vipbuy?channelId=17&cburl=https%3A%2F%2Fdevh5-study.hismarttv.com%2Fmobile%2Fspa%2Fhome%3FdistributeId%3D2000%23%2Fhome%3FopType%3Dios%26&distributeId=2000&srceventcode=206004   页面是通过hash跳转切换的

**Comment by Masterzyy** [comment]
地址参数中无中文

**Comment by WangCao** [comment]
> 正则已修改为[/^https://devh5-study.hismarttv.com/]，还是不能通信

正则写法错误，建议写成  [/devh5-study.hismarttv.com/]

**Comment by Masterzyy** [comment]
> > 正则已修改为[/^https://devh5-study.hismarttv.com/]，还是不能通信
> 
> 正则写法错误，建议写成 [/devh5-study.hismarttv.com/]

你好，请问这个正则具体有什么要求，官网里只写支持正则表达式。我写的正则也都在线匹配过，是没有问题的。

**Comment by Masterzyy** [comment]
> > 正则已修改为[/^https://devh5-study.hismarttv.com/]，还是不能通信
> 
> 正则写法错误，建议写成 [/devh5-study.hismarttv.com/]

写为
![image](https://user-images.githubusercontent.com/31351545/60797900-c1d13d00-a1a2-11e9-8b04-433fb121c6fe.png)也是无法通信的

**Comment by Masterzyy** [comment]
有结论了吗？

**Comment by 77chenmei** [comment]
建议您写个简单demo，测试是否通信。如不能进行通信，可将你的demo发送过来，有我们检测原因。

**Comment by diydyq** [comment]
微信联系中没有收到相关示例的回复，因此关闭；
