### ISSUE TITLE
使用快应用预览版启动页面，不同机型首页加载时间相差较大

### ISSUE THREAD

**Issue by Masterzyy** [quickappcn/issues#42]
### 相关信息
- 问题类型
引擎 

- 引擎版本
预览版1040

- 手机型号
华为mate9
OPPO R9s

- 操作系统

- IDE版本

- toolkit版本

### 问题描述
前提：使用web组件加载页面，在快应用预览版1040上打开
1.预期效果：不同手机机型加载首页的时间相差不多
2.实际结果：机型不同首页加载的时间相差较大，中高端机型首页加载时间1.5秒左右，华为mate9加载时间为2.123s； OPPO R9s首页加载时间为3.681s
### 复现步骤
代码结构:
![image](https://user-images.githubusercontent.com/31351545/60875764-1e009380-a26d-11e9-8c8f-06e6f307c09a.png)
使用web组件加载外部页面，在快应用预览版1040上打开，不同机型首页加载时间相差较大。
中高端机型首页加载时间1.5秒左右，华为mate9加载时间为2.123s； OPPO R9s首页加载时间为3.681s

### 联系方式
微信： z956174725

**Comment by Masterzyy** [comment]
麻烦尽快给出结论

**Comment by Masterzyy** [comment]
使用相同网络，线上环境，测试“汽车之家”快应用：
在Android新款手机，汽车之家快应用首页内容展示时间为：1.2s左右
在Android低端老手机（OPPO R9s）,汽车之家快应用首页内容展示时间为：3.5s左右

**Comment by 77chenmei** [comment]
手机性能不同，处理速度不相同

**Comment by 77chenmei** [comment]
需求已解决，关闭问题；如开发者对此还有问题，请再打开；
