### ISSUE TITLE
有没有类似拖拽排序的sortablelistview 实现拖拽排序功能

### ISSUE THREAD

**Issue by aLLLiyyy** [quickappcn/issues#44]
比如对一个数组进行排序，使用一个list展示，list里面的每个list-item可以相应触摸时间拖拽布局后对数组进行排序

**Comment by lqzerogg** [comment]
嗯，快应用引擎不会考虑做这样的事情。感兴趣的话可以做一个开源出来，也可以联系三方组件库的作者，看看他们有没有兴趣做
