### ISSUE TITLE
在APP中判断快应用是否加桌

### ISSUE THREAD

**Issue by fwshun8023** [quickappcn/issues#45]
### 需求类型
不清楚

### 需求描述
希望提供在APP或者H5中判断快应用是否加桌的方法

### 需求场景
在APP中进行快应用广告的投放时，无法判断快应用是否已加桌，导致很多投放资源的浪费

### 参考
投放app广告可以先判断app是否安装一样

### 联系方式和应用名
微信：Grey-18-28
应用：实况天气预报

**Comment by homercs** [comment]
已有图片编辑接口
https://doc.quickapp.cn/features/system/image.html

**Comment by homercs** [comment]
试试开源实现
https://github.com/xuyisheng/ShortcutHelper
