### ISSUE TITLE
如何将拍照后的图片转为base64格式？

### ISSUE THREAD

**Issue by luffyli** [quickappcn/issues#48]

**Comment by diydyq** [comment]
大概伪代码如下：
      // 字符串转ArrayBuffer
      function str2ab(str) {
        var buf = new ArrayBuffer(str.length);
        var bufView = new Uint8Array(buf);
        for (var i=0, strLen=str.length; i < strLen; i++) {
          bufView[i] = str.charCodeAt(i);
        }
        return buf;
      }
      // ArrayBuffer转字符串
      function ab2str(ab) {
        return String.fromCharCode.apply(null, new Uint8Array(ab));
      }

      const s1 = 'Hello world'
      // 浏览器中的规范：用于和下面对比
      //console.info('btoa：', btoa(s1))
      //console.info('atob：', atob(btoa(s1)))

      console.info('str2ab：', str2ab(s1))
      console.info('ab2str：', ab2str(str2ab(s1)))
      // base64ArrayBuffer()转换ArrayBuffer为Base64；该方法可以在快应用中运行；
      console.info('str2ab：', base64ArrayBuffer(str2ab(s1)))
      // 参考：base64ArrayBuffer方法参考：https://gist.github.com/jonleighton/958841

经过简单验证，上面代码可以正确输出；
先关闭该Issue，后期 @77chenmei  会整体一份该功能到Sample示例中；

**Comment by diydyq** [comment]
补充一下：使用拍照接口后，得到的是照片的uri；可以通过file.readArrayBuffer()读取，然后得到ArrayBufer；

**Comment by zzcode** [comment]
https://qdcto.com/pages/generated_tools/image_to_base64.html 可以使用这个在线工具 图片上传自动转换为base64
