### ISSUE TITLE
request.download 访问需要多次重定向的资源失败

### ISSUE THREAD

**Issue by Benjamin-Zh** [quickappcn/issues#53]
## 问题描述
使用 request.download 下载会发生多次重定向的资源，api 会抛出 { code: 1000, data: "too many redirects" } 错误。测试资源需要进行 6 次重定向。

目前在 vivo、meizu、小米三台设备上进行过测试，vivo、meizu 会抛出此错误，小米能够正常下载资源。

想问下，这个 api 支持的最大重定向次数是多少？开发者是否有办法调整该次数？

**Comment by AndrewTseZhou** [comment]
download 接口使用的是系统下载管理器，无法设置最大重定向次数。

**Comment by Benjamin-Zh** [comment]
好吧 谢谢啦~
