### ISSUE TITLE
希望快应用增加 relaunch api

### ISSUE THREAD

**Issue by Benjamin-Zh** [quickappcn/issues#54]
### 需求类型
引擎

### 需求描述
希望增加类似微信小程序 wx.relaunch 的重启应用 api，或在 router 中集成类似功能。

### 参考
https://developers.weixin.qq.com/miniprogram/dev/api/route/wx.reLaunch.html

**Comment by 77chenmei** [comment]
manifest.json中router.page中设置launchModesingleTask＝singleTask，可以实现这一需求，可参考文档　https://doc.quickapp.cn/framework/manifest.html?h=launchMode

**Comment by AndrewTseZhou** [comment]
@Benjamin-Zh 需求场景是什么
