### ISSUE TITLE
1.5.0.2：web标签下载pdf文件，容器将扩展名错误表示为htm，导致应用体验问题。

### ISSUE THREAD

**Issue by kongzhe607** [quickappcn/issues#57]
同样业务流程，在支付宝里，打开浏览器，保存成pdf文件
在快应用里，拉起系统文件管理，提示保存成.htm文件。

请见附件。

我们的业务需要下载pdf报告给用户，扩展名保存成htm的话，后续无法打开，导致严重的体验问题。
经过与快应用联盟，小米，Andy同学沟通，是容器的错误，请帮助解决，并提示修复进度。

多谢。

**Comment by LDbird** [comment]
问题已知悉，已反馈给前端底层相关同学@andy-yyyy，正在跟进

**Comment by andy-yyyy** [comment]
问题已修复，预计在1060版本中修复该问题。
