### ISSUE TITLE
如何升级 hap-toolkit 至最新

### ISSUE THREAD

**Issue by nicejade** [quickappcn/issues#6]
1. 将本地 `hap-toolkit` 升级至最新如 `0.1.1`: `yarn upgrade hap-toolkit@0.1.1`;
2. 运行 `npx hap update --force` 命令将本地配置升级（会新建 `package.json`, 原文件成 *old package.json*）;  
3. 手动将 *old package.json* 中的自己的额外配置，同步至新的 `package.json`；
4. 将本地的 *node_modules* 和 *package-lock.json*: `rm -rf node_modules`; 
5. 重新安装依赖即可：重新运行 `yarn` or `npm i`;

更多详情可参见： https://github.com/nicejade/vuepress-web-app/issues/16#issuecomment-449814545

**Comment by UncleBill** [comment]
欢迎大家在此对升级过程中遇到的困难提出疑问
