### ISSUE TITLE
transform-origin not work

### ISSUE THREAD

**Issue by laurelL22** [quickappcn/issues#61]
### 相关信息
- 问题类型

- 引擎版本

- 手机型号

- 操作系统

- IDE版本

- toolkit版本

**Comment by LDbird** [comment]
您好，关于transform-origin问题，麻烦描述下您使用的调试器版本号和您是怎么使用的，我这边复现一下问题。

**Comment by laurelL22** [comment]
调试器版本号1.5.0.0，

//  代码
<div class="box" style="{{ ransform: `rotate(${this.centerAngle * this.index}deg)` }}"></box>
.box {
        position: absolute;
        top: 0;
        left: 100px;
        transform-origin: 0px 150px;
}

**Comment by laurelL22** [comment]
// 代码
<div class="box" style="{{  style }}">

style() {
  return {
            transform: `rotate(${this.centerAngle * this.index}deg)`,
            width: `${this.size / 2}px`,
            height: `${this.size / 2}px`,
        }
}


.box { position: absolute; top: 0; left: 100px; transform-origin: 0px 150px; }

**Comment by LDbird** [comment]
您好，此问题已在1060版本修复
