### ISSUE TITLE
richtext直接绑定事件不会触发，事件绑定到richtext父组件也不会触发!!!

### ISSUE THREAD

**Issue by laurelL22** [quickappcn/issues#63]
### 相关信息
- 问题类型

- 引擎版本

- 手机型号

- 操作系统

- IDE版本

- toolkit版本

**Comment by LDbird** [comment]
您好，请问您是在richtext标签上和其父组件标签上写的事件，都没能触发吗？用的什么版本的调试器呢，我这边没复现出来。

**Comment by laurelL22** [comment]
都没有触发，版本是1050

**Comment by LDbird** [comment]
您好，此问题已在1060版本修复
