### ISSUE TITLE
hap-toolkit:0.6.1的源码代码仓什么时候更新下？

### ISSUE THREAD

**Issue by ShourenLan** [quickappcn/issues#64]

**Comment by diydyq** [comment]
请问您的具体需求是什么？方便我们准确定位并进行更新；

**Comment by ShourenLan** [comment]
hap-toolkit现在是编译混合后的代码，源码你们这边有开源的计划吗？

**Comment by diydyq** [comment]
我们目前支持开发者在快应用项目中，通过quickapp.config.js来自定义配置webpack等；
并未收到开放源码的需求；
