### ISSUE TITLE
PC预览与真机环境差异较大

### ISSUE THREAD

**Issue by HandsomeLu** [quickappcn/issues#65]
1.响应位置比实际位置靠上，而且在朋友的电脑上也存在同样问题，应该不是个例
2.在两台笔记本上同样的代码预览效果不同，有一个和真机预览效果差异较大所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。

**Comment by scriptsman** [comment]
@HandsomeLu 能否提供相关截图和代码看下？

**Comment by scriptsman** [comment]
问题较长时间没回复，先暂时关闭。
如果还有问题，可以加微信详谈：vivo-technology
