### ISSUE TITLE
vivo不支持物理返回

### ISSUE THREAD

**Issue by hxlniada** [quickappcn/issues#66]
### 相关信息
- 问题类型
不清楚

- 引擎版本
vivo 所有版本

- 手机型号
vivo 所有机型

- 操作系统
Mac 10.14.6

- IDE版本
IDE 1.7.0 

- toolkit版本
toolkit 0.6.10

### 问题描述
预期：手势返回或者手机右下角返回能触发onBackPress事件
结果：不触发onBackPress。

### 复现步骤
  进入应用点击任意菜单进入二级页面--点击物理返回键无反应，需点击页面左上角返回按钮----审核不通过（所有机型）

### 联系方式
wxid_jjxubw3vp9gc22

**Comment by hxlniada** [comment]
@UncleBill 请问问题排查顺利么？现在vivo审核卡主了过不去

**Comment by limingxiao117** [comment]
wxid_jjxubw3vp9gc22

**Comment by limingxiao117** [comment]
这个微信号（wxid_jjxubw3vp9gc22），没搜不到对应用户，麻烦确认下该联系方式是否正确

**Comment by hxlniada** [comment]
刚确认了下是手势返回不触发，右下角点击是触发的哈，抱歉
