### ISSUE TITLE
没有滚动条距顶部多少像素的事件。类似JS的 scrollTop  

### ISSUE THREAD

**Issue by 18037128621** [quickappcn/issues#67]

**Comment by diydyq** [comment]
请问开发者希望拥有什么样的功能，麻烦描述一下？比如：吸顶；

**Comment by adele-php** [comment]
> 请问开发者希望拥有什么样的功能，麻烦描述一下？比如：吸顶；

比如阅读到底部后，想要回到顶部（不用list里的scrollTo）

**Comment by 18037128621** [comment]
已经解决啦。 是用 OnscrollTo 中的 scrollY值相加得到总的滑动位置值。
