### ISSUE TITLE
background渐变被快应用工具格式化后无法正确展示

### ISSUE THREAD

**Issue by adele-php** [quickappcn/issues#68]
### 相关信息
- 问题类型

不清楚

- 引擎版本

预览版 1060

- 手机型号

xiaomi-MI 6X

- 操作系统

- IDE版本

- toolkit版本

### 问题描述

1.  希望能展现渐变色
```
background: linear-gradient(
          90deg,
          rgba(255, 104, 79, 1),
          rgba(255, 80, 80, 1)
);
```

2.空白

### 复现步骤

将此代码应用到某个div，在快应用开发工具里格式化
```
background: linear-gradient(90deg,rgba(255, 104, 79, 1),rgba(255, 80, 80, 1));
```

**Comment by LDbird** [comment]
问题已复现，稍后给您答复

**Comment by LDbird** [comment]
您好，此问题在hap-toolkit为0.6.14版本修复；目前快应用开发工具的默认toolkit版本是0.6.5，后续会升级默认toolkit版本，在开发工具里您可以先使用一行展示；
