### ISSUE TITLE
list 横向滚动scrollTo无效

### ISSUE THREAD

**Issue by huzewei** [quickappcn/issues#69]
### 相关信息
- 问题类型
list 横向滚动scrollTo无效
IDE  1.7.0
 toolkit：0.6.13

### 复现步骤
1.list 横向滚动
2. click事件触发的scrollTo无问题，在onReady周期中手动调用scrollTo横向不会滚动到指定位置。

### 联系微信
Hzw1043718472

**Comment by LDbird** [comment]
您好，使用官方编辑器已复现问题，会反馈相关人员；请问您那边使用真机调试有这种问题吗？我这边真机测试没问题；

**Comment by huzewei** [comment]
ide连接手机调试能复现，暂时没有真机装包测试

**Comment by LDbird** [comment]
此bug已经在IDE上修复
