### ISSUE TITLE
IDE 预览时 WebSocket 没有正确的构造 ArrayBuffer 类型的下行消息

### ISSUE THREAD

**Issue by leeyeh** [quickappcn/issues#73]
### 相关信息
- 问题类型
IDE

- 操作系统
Mac OS 10.15

- IDE版本
1.9.0

#### 预期
WebSocket 服务端交互的时候设置 WebSocket 的 binaryType 为 `'arraybuffer'` 时，其 onmessage 返回的 data 应该为 ArrayBuffer 类型。
#### 实际效果
data 为 Blob 类型。此外在真机（1060）上没有这个问题。

### 复现步骤
Send an ArrayBuffer to 'wss://echo.websocket.org'. You can see the echoed message is a Blob.

**Comment by LDbird** [comment]
您好，问题已反馈，有结果之后给您答复

**Comment by scriptsman** [comment]
本周版本更新后解决
