### ISSUE TITLE
手机开代理扫码偶尔会提示不再同一个局域网

### ISSUE THREAD

**Issue by techbirds** [quickappcn/issues#74]
开发时会经常设置代理进行联调，会影响开发体验。

**Comment by LDbird** [comment]
您好，调试的时候手机跟电脑需要处于同一局域网内；如果不能保证在同一个局域网内，打开【快应用调试器】，点击打开【开启USB调试】模式开关；您那边说的手机开代理扫码是指什么情况呢？麻烦留一下您的联系方式。

**Comment by techbirds** [comment]
就是使用手机内置的全局代理，是一个局域网内。

然后PC端起服务，然后通过手机扫码有时候会提示不再同一个局域网。

**Comment by LDbird** [comment]
您好，Android手机上开启全局代理，有可能会有不稳定的情况；
