### ISSUE TITLE
两个自定义组件之间不能通信

### ISSUE THREAD

**Issue by mwang0** [quickappcn/issues#77]
### 相关信息
- 前端组件 

- meizu 1063 

- meizu 16x

-  Mac OS 10.13.6

- IDE 1.6.0

- toolkit 0.4.7

### 问题描述
1. 预期效果：在页面上 自定义组件A 嵌套 自定义组件B， AB两个组之间能正常通信
2.实际效果：
     - 在B组件内通过 this.$parent() 方法 或 遍历$parent() 未能正确获得A组件; 
     - 在B组件内调用 this.$dispatch('test') , A组件监听 this.$on('test',()=>console.log('ok')), A组件收不到事件

### 复现步骤
```
A组件: 
<template> 
  <div><slot></slot><div>
</template>

<script>
export default{

  onInit(){
    this.$on('test', (evt)=>{
      evt.stop()
      console.log('test')
      // 收不到事件
    })
  }
}
</script>

// B组件: 
<template> 
  <div>
    <text>test</text>
  </div>
</template>
<script>
onInit(){
// onReady(){  
  const parent = this.$parent()
  this.$dispatch('test')
  console.log(parent)  // 不是A
  console.log(parent.$parent())  // 输出 undefined
}
</script>

//Page页:
<import name="AComponent" src="./a"></import>
<import name="BComponent" src="./b"></import>
<template> 
  <div>
    <a-component>
      <b-component></b-component>
    </a-component>
  </div>
</template>


### 联系方式
微信号: cn_mwang

**Comment by LDbird** [comment]
您好，看了您的代码，您是在Page页中引入的组件A和组件B，所以父组件是Page页，通过this.$parent()获取到的是Page页的ViewModel；也是在Page页接收到组件B的通信；
如果您想获取组件A的ViewModel，在组件A中接收到组件B的通信，可以在组件A中引入组件B；
您可以看下‘’组件通信‘’的官方文档：https://doc.quickapp.cn/tutorial/framework/parent-child-component-communication.html
