### ISSUE TITLE
安全需求

### ISSUE THREAD

**Issue by crx12345678** [quickappcn/issues#8]
文档关于:

- [x] 缺失
- [ ] 错误
- [ ] 不确定？

### 详细描述
快应用读取androidsocket开放端口，接收或发送数据时会遭到远程攻击
### 你的提议和看法
1、数据读取添加与android端直接传递的方法
2、在快应用中添加验证方法来进行过滤（类似于socket开放端口接收的数据的过滤）

**Comment by xiaomin8676** [comment]
@crx12345678 你好，感谢反馈，我是快应用联盟厂商vivo的开发人员，希望了解下详情，我的邮箱 xiaomin@vivo.com
另外，在厂商修复前，还请不要对快应用联盟厂商之外的人员公布详情，谢谢！

**Comment by diydyq** [comment]
未收到更新，因此关闭；
