### ISSUE TITLE
hap-toolkit-client-records.json文件位置不对

### ISSUE THREAD

**Issue by fuzideng** [quickappcn/issues#80]
Issue Type: <b>Bug</b>

手机扫描调试后，生成hap-toolkit-client-records.json文件。hap-toolkit-client-records.json文件存放目录不规范，直接生成在$HOME目录。

quickapp IDE version: 快应用开发工具 1.8.0 (52845e50ac254c56959554604fad322aec6b383d, 2019-12-26T07:08:28.258Z)
OS version: Linux x64 5.3.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|15.50GB (0.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.25.1
githistory|don|0.4.4
prettier-vscode|esb|1.7.3
hap-projects|Hap|1.1.1
hap-vivo-stf|Hap|1.1.0

</details>

**Comment by LDbird** [comment]
您好，问题已知悉，有结论后给您答复；

**Comment by LDbird** [comment]
您好，咨询得到的结论是：IDE设计的就是hap-toolkit-client-records.json文件在用户目录下，这是属于正常现象；
