### ISSUE TITLE
打开ide就会黑屏

### ISSUE THREAD

**Issue by NiceGuSheng** [quickappcn/issues#82]
Issue Type: <b>Bug</b>

打开ide后经常会黑屏，严重影响使用

VS Code version: 快应用开发工具 2.0.0 (a83ac16ac266df5d542ed48e6fea91539e09fc59, 2020-03-17T14:16:06.871Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.75GB (0.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by LDbird** [comment]
您好，ide黑屏问题，建议先设置 search.followSymlinks为false；

**Comment by NiceGuSheng** [comment]
已经设置过&nbsp;&nbsp;search.followSymlinks为false&nbsp;了 ，没有效果还是会出现黑屏，刚开始是点击Devtools的时候才会黑屏，后来直接打开就会频繁的黑屏，卸载安装了几次还是不行。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LDbird"<notifications@github.com&gt;; 
发送时间: 2020年4月16日(星期四) 下午4:52
收件人: "quickappcn/issues"<issues@noreply.github.com&gt;; 
抄送: "1178616748"<1178616748@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [quickappcn/issues] 打开ide就会黑屏 (#82)





 
您好，ide黑屏问题，建议先设置 search.followSymlinks为false；

**Comment by LDbird** [comment]
在argv.json文件中配置  "disable-hardware-acceleration": true  试下

**Comment by NiceGuSheng** [comment]
你好 没有找到argv.json文件呢

**Comment by LDbird** [comment]
最新版本没有黑屏问题；您IDE升级到最新版本即可；
