### ISSUE TITLE
sms 文档示例中sms.send方法，address 和 content字段后面冒号是汉字字符

### ISSUE THREAD

**Issue by dream-worker** [quickappcn/issues#84]
文档关于:

- [发送短信](https://doc.quickapp.cn/features/system/sms.html)

- [ ] 缺失
- [x] 错误
- [ ] 不确定？

### 详细描述
- sms 文档示例中sms.send方法，address 和 content字段后面冒号是汉字字符

### 你的提议和看法
字段后面冒号改为**英文冒号**

**Comment by LDbird** [comment]
问题已知悉，我们这边会修改文档为英文冒号，感谢您的反馈；

**Comment by LDbird** [comment]
文档已修改
