### ISSUE TITLE
初始化的DEMO项目一直在编译中

### ISSUE THREAD

**Issue by ImChrisChen** [quickappcn/issues#95]
Issue Type: <b>Bug</b>

新建快应用工程后，模拟器一直在编译中

VS Code version: 快应用开发工具 3.0.0 (6a8af2336fbc3c8565c68cc5f612772f1c34ff51, 2020-05-23T03:18:38.998Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vim|vsc|0.16.10

</details>

**Comment by Jerome77777** [comment]
安装了npm依赖了吗

**Comment by LDbird** [comment]
解决方法：
1. 打开目录 C:\Users\{ user }\AppData\Roaming\快应用开发工具
2. 删除目录下所有文件，仅保留 userid
3. 重启 IDE
