### ISSUE TITLE
USB调试数据线连接手机后IDE提示没有安卓设备，之后就一直显示正在编译，卸载重装都没用。MacOS

### ISSUE THREAD

**Issue by heweimin** [quickappcn/issues#97]
Issue Type: <b>Bug</b>

USB调试数据线连接手机后IDE提示没有安卓设备，之后就一直显示正在编译，卸载重装都没用。MacOS

VS Code version: 快应用开发工具 3.0.0 (6a8af2336fbc3c8565c68cc5f612772f1c34ff51, 2020-05-23T03:18:38.998Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|16.00GB (2.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
hap-apks|Hap|0.0.4
hap-projects|Hap|1.2.2
hap-transfomer|Hap|1.2.18

</details>

**Comment by LDbird** [comment]
您好，您的手机有没有在“开发者选项”中打开USB调试呢？删除node-mudoles重新npm install，然后再运行试下
