### ISSUE TITLE
Error: command 'extension.hapdebug.buildRpk' not found

### ISSUE THREAD

**Issue by heweimin** [quickappcn/issues#98]
Issue Type: <b>Bug</b>

Error: command 'extension.hapdebug.buildRpk' not found是什么问题？怎么解决，求指点

VS Code version: 快应用开发工具 3.0.0 (6a8af2336fbc3c8565c68cc5f612772f1c34ff51, 2020-05-23T03:18:38.998Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (1.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
hap-chimera-toolkit|Hap|1.0.0
hap-apks|Hap|0.0.4
hap-projects|Hap|1.2.2
hap-transfomer|Hap|1.2.18

</details>

**Comment by LDbird** [comment]
您好，您是什么情境下出现这个问题呢？麻烦加下我微信：15701638991；

**Comment by heweimin** [comment]
进~/Library/ApplicationSupport/快应用开发工具，把目录下除了userid 外的其他都删掉，然后重启IDE就OK了
