### ISSUE TITLE
win10下IDE的DEVTOOLS栏在没有模拟器栏的情况下，被拉伸

### ISSUE THREAD

**Issue by tnjin** [quickappcn/issues#99]
Issue Type: <b>Bug</b>

1.正常启动IDE
2.关闭模拟器
3.切换IDE底部的调试栏到 DEVTOOLS标签，会发现DEVTOOLS被拉伸，不能正常展示，且不能点击

![image](https://user-images.githubusercontent.com/3954881/85943446-c027f880-b962-11ea-9efa-3c7b17265810.png)

VS Code version: 快应用开发工具 3.0.0 (6a8af2336fbc3c8565c68cc5f612772f1c34ff51, 2020-05-22T09:54:18.743Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (4.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.4
hap-vivo-stf|Hap|1.2.0

</details>

**Comment by LDbird** [comment]
您好，devtools就是模拟器的；关闭模拟器，不显示devtools是正常现象；
IDE 3.0.0表现如下
![image](https://user-images.githubusercontent.com/48194592/85944077-d8017b80-b966-11ea-97ba-b5b8279593cb.png)
